/* eslint-disable @typescript-eslint/naming-convention */
export const setlistNames = {
	'311hero': '311 Hero',
	'a2z': 'A-Z packs',
	'a7x': 'A7X Hero',
	'A9 ': 'Asphalt 9: Legends',
	'ab': 'Aeon Bridge Discography',
	'adagiodiscog': 'Adagio Discography',
	'ae': 'Avatar Emporium',
	'aep': 'Eternalized',
	'ah1': 'Angevil Hero',
	'ah2': 'Angevil Hero 2',
	'ah3': 'Angevil Hero 3',
	'ah4': 'Angevil Hero 4',
	'ah5': 'Angevil Hero 5',
	'ahbe': 'Anti Hero: Beach Episode',
	'altquest': 'Alt Quest',
	'anime': 'RdNetwork\'s Anime/Weeb charts',
	'animehero': 'Anime Hero',
	'antihero': 'Anti Hero',
	'antihero2': 'Anti Hero 2',
	'attentionspan': 'Attention Span',
	'b-m': 'Band-Maid',
	'bh': 'Band Hero',
	'bhdlc': 'Band Hero - DLC',
	'bhds': 'Band Hero DS',
	'bitcrusher': 'Bitcrusher',
	'bitcrusherdlc': 'Bitcrusher DLC',
	'blackhole': 'Black Hole',
	'bnew': 'Brand New Hero',
	'bodom': 'Bodom Hero',
	'bs': 'Blanket Statement',
	'casp': 'Community Artists and Streamers Project',
	'catalyst': 'Catalyst',
	'cavequest': 'Cave Quest',
	'cb': 'Circuit Breaker',
	'ccc': 'Customs Creator Collective',
	'ch-on': 'CH-ON',
	'ch': 'Clone Hero',
	'chan': 'CHAN',
	'charts': 'C.H.A.R.T.S.',
	'charts2': 'C.H.A.R.T.S. 2',
	'chelhero': 'Chel Hero',
	'chilehero': 'Chile Hero',
	'clc': 'CamLikesCow Chart Pack',
	'clonmania': 'Clonmania',
	'cm20': 'CLUB_MIX2',
	'cm300': 'CLUB_MIX3',
	'cob': 'Children Of Bodom',
	'codered': 'Code Red',
	'cowhero': 'Cow Hero',
	'cowherodlc1': 'Cow Hero - DLC 1',
	'cowherodlc2': 'Cow Hero - DLC 2',
	'cowherodlc3': 'Cow Hero - DLC 3',
	'creativech': 'Creative Commons Hero',
	'crystall': 'Crystallizer',
	'csc': 'Custom Songs Central',
	'csp': 'Community Snack Pack',
	'cst': 'Cover Setlist Team',
	'cth1': 'Carpal Tunnel Hero',
	'cth1r': 'Carpal Tunnel Hero: Remastered',
	'cth2': 'Carpal Tunnel Hero 2',
	'cth3': 'Carpal Tunnel Hero 3',
	'cth3dlc': 'Carpal Tunnel Hero 3 DLC',
	'ctp6': 'Community Track Pack 6',
	'dcr': 'Delta\'s Chart Repository',
	'ddlc': 'Doki Doki Literature Club',
	'dfch': 'DragonForce Discography Rechart',
	'dfd': 'DragonForce Discography Setlist',
	'DHC': 'Djent Hero Collection',
	'dhc': 'Djent Hero Collection',
	'digi': 'Digitizer',
	'disgo': 'Disgorodraphy',
	'dissonancehero': 'Dissonance Hero',
	'djenthero': 'Djent Hero',
	'djentherodlc': 'Djent Hero - DLC',
	'djh': 'DJ Hero',
	'djmax': 'DJMax Pack',
	'doomhero': 'Doom Hero',
	'dp9': 'Drum Project IX',
	'eds': 'Ensiferum Discography Setlist',
	'efhiii': 'EFHIII',
	'enh': 'Endless Hero',
	'extremehero': 'Extreme Hero',
	'fab4disc': 'FAB4DISC',
	'facelift': 'Facelift',
	'FF': 'Final Fantasy: OST Hero',
	'fo2': 'FlatOut 2 Soundtrack',
	'fof': 'Frets on Fire',
	'fp': 'Focal Point',
	'fp2': 'Focal Point 2',
	'fp2dh': 'Focal Point 2.DHumanity',
	'fp3': 'Focal Point 3',
	'france': 'RdNetwork\'s French charts',
	'french': 'HexaNation',
	'fruitsnacks': 'Razzy\'s Fruit Snacks',
	'fuse': 'Fuse Box',
	'GameChanger': 'Game Changer',
	'gd': 'GITADORA',
	'gdrb': 'Green Day: Rock Band',
	'gdrbdlc': 'Green Day: Rock Band - DLC',
	'gdrbold': 'Green Day: Rock Band (old)',
	'gf1': 'GuitarFreaks',
	'gf2dm1': 'GuitarFreaks 2ndMIX & DrumMania',
	'gh_hero': 'Guitar Hero Hero',
	'gh1': 'Guitar Hero I',
	'gh2': 'Guitar Hero II',
	'gh2dlc': 'Guitar Hero II - DLC',
	'gh3': 'Guitar Hero III: Legends of Rock',
	'gh3dlc': 'Guitar Hero III - DLC',
	'gh5': 'Guitar Hero 5',
	'gh5dlc': 'Guitar Hero 5 - DLC',
	'gh80s': 'Guitar Hero Encore: Rocks the 80s',
	'gha': 'Guitar Hero: Aerosmith',
	'ghl': 'Guitar Hero Live',
	'ghm': 'Guitar Hero: Metallica',
	'ghmdlc': 'Guitar Hero: Metallica - DLC',
	'ghot': 'Guitar Hero: On Tour',
	'ghotd': 'Guitar Hero On Tour: Decades',
	'ghotmh': 'Guitar Hero On Tour: Modern Hits',
	'ghsh': 'Guitar Hero: Smash Hits',
	'ghtv': 'Guitar Hero TV',
	'ghvh': 'Guitar Hero: Van Halen',
	'ghwor': 'Guitar Hero: Warriors of Rock',
	'ghwordlc': 'Guitar Hero: Warriors of Rock DLC',
	'ghwt': 'Guitar Hero: World Tour',
	'ghwtdlc': 'Guitar Hero: World Tour DLC',
	'ghx2setlist': 'Guitar Hero X 2',
	'ghxsetlist': 'Guitar Hero X',
	'gp': 'Guitar Praise',
	'guitarknight': 'Guitar Knight',
	'guitarzero2': 'Guitar Zero 2',
	'guitarzerodlc': 'Guitar Zero 2 DLC',
	'gybe': 'Godspeed You! Black Emperor Discography',
	'harmonyhero': 'Harmony Hero',
	'heavyloadhero': 'Heavy Load Hero',
	'hyenahero': 'Hyena Hero',
	'igniter': 'Igniter',
	'imetal': 'Instru-Metal',
	'indoproject': 'I\'M INDONESIA',
	'isotope': 'Isotope',
	'jarts': 'Jarts',
	'jbs': 'JoJo\'s Bizarre Adventure Part 1: Phantom Blood Chart Pack',
	'jrb ': 'J-Rock Band',
	'kh': 'Koreaboo Hero',
	'kh2': 'Koreaboo Hero 2',
	'kldd': 'KILL LINCOLN - DESTRUCTIVE DELUXE',
	'klok': 'Klok Hero',
	'lb': 'Lovebites',
	'lisarb': 'LISARB',
	'lisarb2': 'LISARB 2',
	'lisarb3': 'LISARB 3',
	'log': 'Lamb of God',
	'lprb': 'Linkin Park Rock Band',
	'lrb': 'LEGO Rock Band',
	'lrbdlc': 'LEGO Rock Band - DLC',
	'lsimulator': 'Lawnmower Simulator',
	'ma': 'Max Altitude',
	'mania': 'Mania Hero',
	'marathon': 'Marathon Hero',
	'marathonhero2': 'Marathon Hero 2',
	'marfgh': 'marfGH',
	'marfvol0': 'marfGH: Volume 0',
	'marfvol1': 'marfGH: Volume 1',
	'marfvol2': 'marfGH: Volume 2',
	'marfvol3': 'marfGH: Volume 3',
	'marfvol4': 'marfGH: Volume 4',
	'meshuggah': 'Meshuggah Discography',
	'metallicadiscog': 'Guitar Hero Metallica: Complete Edition',
	'mh_aren': 'Mania Hero',
	'mh_asriel': 'Mania Hero',
	'mh_dex': 'Mania Hero',
	'mh_fluffy': 'Mania Hero',
	'mh_ori': 'Mania Hero',
	'mh_sasquatch': 'Mania Hero',
	'mh_sickliff': 'Mania Hero',
	'mh_skittlecouch': 'Mania Hero',
	'mh_supra': 'Mania Hero',
	'mh2': 'Marathon Hero 2',
	'miscellaneous': 'Miscellaneous Packs',
	'monstercat': 'Monstercat',
	'ms3': 'Monstrão of Rock 3',
	'ms4': 'Monstrão of Rock 4',
	'newbeat': 'New Beat',
	'nirvanasp': 'Nirvana Discography',
	'nowave': 'No Wave Song Pack',
	'osthero': 'OST Hero',
	'pah': 'Plastarists Anonymous Hero',
	'paradigm': 'Paradigm',
	'peckhero': 'Peck Hero',
	'pedahero': 'Peda Hero',
	'pg': 'Power Gig: Rise of the SixString',
	'pgh2': 'Project Remaster: Guitar Hero II',
	'ph': 'Parallax Hero',
	'ph1': 'Puppetz Hero I',
	'ph2': 'Puppetz Hero II',
	'ph3': 'Puppetz Hero III',
	'ph4': 'Puppetz Hero IV',
	'phaseshift': 'Phase Shift Setlist',
	'phc': 'Plastic Hero',
	'phcg': 'Plastic Hero (Full Band)',
	'phcs': 'Plastic Hero (Duos)',
	'phdlc': 'Parallax Hero DLC',
	'phishballad': 'PhxPhishPhan\'s Ballad Pack REDUX',
	'pile_of_hearts': 'The Void Rains Upon Her Heart',
	'polkadot': 'POLKADOT STINGRAY Discography',
	'pp': 'Phoenix Protocol',
	'praise': 'Guitar Praise',
	'psgp2': 'Phase Shift Guitar Project 2',
	'psgp3': 'Phase Shift Guitar Project 3',
	'psgp4': 'Phase Shift Guitar Project 4',
	'PSH': 'Plastic Shred Hero: Legends of Apathetic Charting',
	'PSH2': 'Plastic Shred hero 2',
	'pstr': 'Project Strandberger',
	'ra': 'Redemption Arc',
	'ragequit': 'Rage Quit',
	'rb1': 'Rock Band 1',
	'rb1dlc': 'Rock Band 1 - DLC',
	'rb2': 'Rock Band 2',
	'rb2dlc': 'Rock Band 2 - DLC',
	'rb3': 'Rock Band 3',
	'rb3dlc': 'Rock Band 3 - DLC',
	'rb4': 'Rock Band 4',
	'rb4dlc': 'Rock Band 4 - DLC',
	'rbacdc': 'AC/DC Live: Rock Band Track Pack',
	'rbb': 'Rock Band Blitz',
	'rbdlc': 'Rock Band - DLC',
	'rbn': 'Rock Band Network',
	'revolved': 'REVOLVED',
	'rocklist': 'Rocklist',
	'rr': 'Rock Revolution',
	'rsp': 'Russian Song Pack',
	's_hero': 'S Hero',
	's_hero2': 'S Hero 2',
	's64': 'Shredz64',
	'ScoreSpy': 'ScoreSpy',
	'scu': 'Small Charters United',
	'scufd': 'Small Charters United (Full Difficulty)',
	'sdvx1': 'Sound Voltex 1',
	'sdvx3': 'Sound Voltex 3',
	'sdvx4': 'Sound Voltex 4',
	'sdvx5': 'Sound Voltex 5',
	'se': 'Symphonic Effect',
	'shortcircuit': 'Short Circuit',
	'shurikenhero': 'Shuriken Hero',
	'soadrb': 'System of a Down Rock Band',
	'soi': 'Shadow of Intent Discography',
	'soz1': 'State of Zen 1',
	'soz2': 'State of Zen 2',
	'spcted': 'Space Teddy',
	'stems': 'S.T.E.M. PROJECT',
	'stratodiscog': 'Stratovarius Discography',
	'swcb': 'SwooshyCueb',
	'sxdisc': 'Symphony X Discography',
	'synergy': 'Synergy',
	'tbrb': 'The Beatles: Rock Band',
	'tbrbcdlc': 'The Beatles: Rock Band Custom DLC Project',
	'tbrbdlc': 'The Beatles: Rock Band - DLC',
	'tds': 'Technical Difficulties Series Packs',
	'tfoth': 'The Fall of Troy Hero',
	'tfothplus': 'The Fall of Troy Hero +',
	'thch': 'Tony Hawk\'s Clone Hero',
	'thehero': 'The Hero',
	'thps12': 'Tony Hawk\'s Pro Skater 1+2 Soundtrack',
	'tmdiscog': 'Tokyo Machine Discography',
	'transistor': 'Transistor',
	'um': 'Unlucky Morpheus',
	'unsung': 'Unsung Hero',
	'vortex_hero': 'Vortex Hero',
	'vtm': '/v/',
	'vu': 'Verified Unverified',
	'wcc': 'World Charts Community',
	'wccg': 'World Charts Community',
	'wccs': 'World Charts Community',
	'weebs': 'Oops! All Weeb!',
	'wh': 'Weed Hero',
	'wh2': 'Weed Hero 2',
	'yis2': 'YouTube Italia Sings 2',
	'z': 'zDLC™',
	'Zancharted': 'Zancharted',
	'zancharted': 'Zancharted',
	'zerogravity': 'Zero Gravity',
	'zg3d': 'Zero Gravity: 3D',
	'zgsb': 'Zero Gravity: Space Battle',
} as { [icon: string]: string }
