/* eslint-disable @typescript-eslint/naming-convention */
export const setlistNames = {
	'311hero': '311 Hero',
	'a7x': 'A7X Hero',
	'ae': 'Avatar Emporium',
	'aep': 'Eternalized',
	'ah1': 'Angevil Hero',
	'ah2': 'Angevil Hero 2',
	'ah3': 'Angevil Hero 3',
	'ah4': 'Angevil Hero 4',
	'ah5': 'Angevil Hero 5',
	'ahbe': 'Antihero: Beach Episode',
	'anime': 'RdNetwork\'s Anime/Weeb charts',
	'antihero': 'Antihero',
	'antihero2': 'Antihero 2',
	'b-m': 'Band-Maid',
	'bh': 'Band Hero',
	'bhdlc': 'Band Hero - DLC',
	'bhds': 'Band Hero DS',
	'blackhole': 'Black Hole',
	'bodom': 'Bodom Hero',
	'bs': 'Blanket Statement',
	'casp': 'Community Artists and Streamers Project',
	'cavequest': 'Cave Quest',
	'cb': 'Circuit Breaker',
	'ccc': 'Customs Creators Collective',
	'ch-on': 'CH-ON',
	'chan': 'CHAN',
	'charts': 'C.H.A.R.T.S.',
	'charts2': 'C.H.A.R.T.S. 2',
	'chilehero': 'Chile Hero',
	'cob': 'Children Of Bodom',
	'codered': 'Code Red',
	'cowhero': 'Cow Hero',
	'cowherodlc1': 'Cow Hero - DLC 1',
	'cowherodlc2': 'Cow Hero - DLC 2',
	'cowherodlc3': 'Cow Hero - DLC 3',
	'creativech': 'Creative Commons Hero',
	'csc': 'Custom Songs Central',
	'cst': 'Cover Setlist Team',
	'cth1': 'Carpal Tunnel Hero',
	'cth1r': 'Carpal Tunnel Hero: Remastered',
	'cth2': 'Carpal Tunnel Hero 2',
	'cth3': 'Carpal Tunnel Hero 3',
	'ctp6': 'Community Track Pack 6',
	'ddlc': 'Doki Doki Literature Club',
	'dfch': 'DragonForce Discography Rechart',
	'dhc': 'Djent Hero Collection',
	'digi': 'Digitizer',
	'dissonancehero': 'Dissonance Hero',
	'djenthero': 'Djent Hero',
	'djentherodlc': 'Djent Hero - DLC',
	'djh': 'DJ Hero',
	'djmax': 'DJMax Pack',
	'doomhero': 'Doom Hero',
	'dp9': 'Drum Project IX',
	'eds': 'Ensiferum Discography Setlist',
	'efhiii': 'EFHIII',
	'enh': 'Endless Hero',
	'extremehero': 'Extreme Hero',
	'fab4disc': 'FAB4DISC',
	'facelift': 'Facelift',
	'fo2': 'FlatOut 2 Soundtrack',
	'fof': 'Frets on Fire',
	'fp': 'Focal Point',
	'fp2': 'Focal Point 2',
	'france': 'RdNetwork\'s French charts',
	'french': 'HexaNation',
	'fuse': 'Fuse Box',
	'gdrb': 'Green Day: Rock Band',
	'gdrbdlc': 'Green Day: Rock Band - DLC',
	'gdrbold': 'Green Day: Rock Band (old)',
	'gf1': 'GuitarFreaks',
	'gf2dm1': 'GuitarFreaks 2ndMIX & DrumMania',
	'gh1': 'Guitar Hero I',
	'gh2': 'Guitar Hero II',
	'gh2dlc': 'Guitar Hero II - DLC',
	'gh3': 'Guitar Hero III',
	'gh3dlc': 'Guitar Hero III - DLC',
	'gh5': 'Guitar Hero 5',
	'gh5dlc': 'Guitar Hero 5 - DLC',
	'gh80s': 'Guitar Hero Encore: Rocks the 80s',
	'gha': 'Guitar Hero: Aerosmith',
	'ghl': 'Guitar Hero Live',
	'ghm': 'Guitar Hero: Metallica',
	'ghmdlc': 'Guitar Hero: Metallica - DLC',
	'ghot': 'Guitar Hero: On Tour',
	'ghotd': 'Guitar Hero On Tour: Decades',
	'ghotmh': 'Guitar Hero On Tour: Modern Hits',
	'ghsh': 'Guitar Hero: Smash Hits',
	'ghtv': 'Guitar Hero TV',
	'ghvh': 'Guitar Hero: Van Halen',
	'ghwor': 'Guitar Hero: Warriors of Rock',
	'ghwordlc': 'Guitar Hero: Warriors of Rock - DLC',
	'ghwt': 'Guitar Hero: World Tour',
	'ghwtdlc': 'Guitar Hero: World Tour - DLC',
	'ghxsetlist': 'Guitar Hero X',
	'gp': 'Guitar Praise',
	'guitarzero2': 'Guitar Zero 2',
	'guitarzerodlc': 'Guitar Zero - DLC',
	'heavyloadhero': 'Heavy Load Hero',
	'jbs': 'JoJo\'s Bizarre Adventure Part 1: Phantom Blood Chart Pack',
	'kh': 'Koreaboo Hero',
	'kh2': 'Koreaboo Hero 2',
	'kldd': 'KILL LINCOLN - DESTRUCTIVE DELUXE',
	'klok': 'Klok Hero',
	'lb': 'Lovebites',
	'lisarb': 'LISARB',
	'lisarb2': 'LISARB 2',
	'lisarb3': 'LISARB 3',
	'log': 'Lamb of God',
	'lrb': 'LEGO Rock Band',
	'lrbdlc': 'LEGO Rock Band - DLC',
	'ma': 'Max Altitude',
	'mania': 'Mania Hero',
	'marathon': 'Marathon Hero',
	'marathonhero2': 'Marathon Hero 2',
	'mh2': 'Marathon Hero 2',
	'mh_aren': 'Mania Hero',
	'mh_asriel': 'Mania Hero',
	'mh_dex': 'Mania Hero',
	'mh_fluffy': 'Mania Hero',
	'mh_ori': 'Mania Hero',
	'mh_sasquatch': 'Mania Hero',
	'mh_sickliff': 'Mania Hero',
	'mh_skittlecouch': 'Mania Hero',
	'mh_supra': 'Mania Hero',
	'monstercat': 'Monstercat',
	'ms3': 'Monstrão of Rock 3',
	'ms4': 'Monstrão of Rock 4',
	'newbeat': 'New Beat',
	'nirvanasp': 'Nirvana Full Discography',
	'osthero': 'OST Hero',
	'peckhero': 'Peck Hero',
	'pedahero': 'Peda Hero',
	'pg': 'Power Gig: Rise of the SixString',
	'pgh2': 'Project Remaster: Guitar Hero II',
	'ph': 'Parallax Hero',
	'ph1': 'Puppetz Hero I',
	'ph2': 'Puppetz Hero II',
	'ph3': 'Puppetz Hero III',
	'ph4': 'Puppetz Hero IV',
	'phaseshift': 'Phase Shift Setlist',
	'phishballad': 'PhxPhishPhan\'s Ballad Pack REDUX',
	'psgp2': 'Phase Shift Guitar Project 2',
	'psgp3': 'Phase Shift Guitar Project 3',
	'psgp4': 'Phase Shift Guitar Project 4',
	'pstr': 'Project Strandberger',
	'ra': 'Redemption Arc',
	'rb1': 'Rock Band 1',
	'rb1dlc': 'Rock Band 1 - DLC',
	'rb2': 'Rock Band 2',
	'rb2dlc': 'Rock Band 2 - DLC',
	'rb3': 'Rock Band 3',
	'rb3dlc': 'Rock Band 3 - DLC',
	'rb4': 'Rock Band 4',
	'rb4dlc': 'Rock Band 4 - DLC',
	'rbacdc': 'AC/DC Live: Rock Band Track Pack',
	'rbb': 'Rock Band: Blitz',
	'rbdlc': 'Rock Band - DLC',
	'rbn': 'Rock Band Network',
	'revolved': 'Revolved',
	'rocklist': 'Rocklist',
	'rr': 'Rock Revolution',
	'rsp': 'Russian Songs Pack',
	'sdvx1': 'Sound Voltex 1',
	'sdvx3': 'Sound Voltex 3',
	'sdvx4': 'Sound Voltex 4',
	'sdvx5': 'Sound Voltex 5',
	'se': 'Symphonic Effect',
	'soz1': 'State of Zen 1',
	'soz2': 'State of Zen 2',
	'spcted': 'Space Teddy',
	'stems': 'S.T.E.M. PROJECT',
	'swcb': 'SwooshyCueb',
	'sxdisc': 'Symphony X Discography Setlist',
	'tbrb': 'The Beatles: Rock Band',
	'tbrbdlc': 'The Beatles: Rock Band - DLC',
	'tds': 'Technical Difficulties Series Packs',
	'tfoth': 'The Fall of Troy Hero',
	'tmdiscog': 'Tokyo Machine Discography',
	'um': 'Unlucky Morpheus',
	'unsung': 'Unsung Hero',
	'vortex_hero': 'Vortex Hero',
	'vu': 'Verified Unverified',
	'wcc': 'World Charts Community',
	'wccg': 'World Charts Community',
	'wccs': 'World Charts Community',
	'wh': 'Weed Hero',
	'wh2': 'Weed Hero 2',
	'zerogravity': 'Zero Gravity',
	'zgsb': 'Zero Gravity: Space Battle',
} as { [icon: string]: string }
